### ISSUE TITLE
"Start time can't be empty", but time_entry_start_hour has some value

### ISSUE THREAD

**Issue by viktorkho** [nicStuff/redmine_timesheet_extensions#29]
Redmine 1.3.2 clean instalation 
redmine_timesheet_extensions installed as described at wiki page
All the fields at http://redmine.mypc/issues/1/time_entries/new has any values
After clicking "Save" I have "Start time can't be empty" error..

At this time in tail -f log/production.log:
[...]
Processing TimelogController#create (for 192.168.2.222 at 2012-07-17 17:25:47) [POST]
  Parameters: {"time_entry"=>{"billed_hours"=>"1", "comments"=>"commmment", "issue_id"=>"1", "end_minute"=>"0", "activity_id"=>"8", "start_hour"=>"0", "spent_on"=>"2012-07-17", "start_minute"=>"0", "hours"=>"1", "end_hour"=>"1"}, "back_url"=>"http%3A%2F%2F192.168.2.235%3A3000%2Fissues%2F1", "commit"=>"Save", "project_id"=>"demo", "action"=>"create", "authenticity_token"=>"dG58ciRg0yxcVMXt9hlQIr9zCY+j9PEKLaQ6kpuRR+s=", "controller"=>"timelog"}
[...]

What can I do to fix this trouble?

**Comment by nicStuff** [comment]
If you can, please install redmine 2.0.3 and use the plugin from the branch "redmine-2.0.3": it is updated and is more correct than the master branch's version.

Anyway, this issue is related to how the incoming request attributes are handled by the timelog controller: it uses "safe_attributes" method by the 1.3.2 version. Copy the [code of the time entry patch of branch 2.0.3](https://github.com/nicStuff/redmine_timesheet_extensions/blob/redmine-2.0.3/lib/time_entry_patch.rb), it should work fine even for 1.3.2.

**Comment by viktorkho** [comment]
> Copy the code of the time entry path of branch 2.0.3..

Thanks a lot! Problem was solved on v132..
